#!/bin/sh

usb1=$(lsblk -la | awk '/sdc1/ { print $1 }')
usb1mounted=$(lsblk -la | awk '/sdc1/ { print $7 }')

if [ "$usb1" ]; then
	if [ -z "$usb1mounted" ]; then
		echo "  "
	else
		echo "  $usb1 "
	fi
fi
